FROM pipdevs/ts-dev:2.5.2

# set working directory
WORKDIR /app
# copy project file
COPY package.json .
 
# install ALL node_modules, including 'devDependencies'
RUN npm install

# copy all project
COPY . .
# compile source code
RUN  tsc
